### ISSUE TITLE
Ember Bootstrap v6

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#1840]
Let's compile a list of breaking changes, which we want to ship in the next major release.

- [x] Drop support for node 12 (#1838)
- [x] Drop support for Ember 3.24 (#1839)
- [x] ~~Add peer dependency on `@ember/string` (#1845)~~ (not necessary thanks to #1849)
- [x] Adjust BS4 markup for `<BsAccordion>` to Bootstrap docs (#1844)
- [ ] check our use of dependencies, especially with regard to peerDependencies. Some things we have as a dependency should probably be a peerDependency (e.g. `@glimmer/component`), which could be seen as a breaking change.
  *I enjoy the privilege of having the SME (subject matter expert) on pnpm and peerDependencies as a collegue (@nullvoxpopuli), so he might be able to advise?*
- [ ] ~~`{ importBootstrapCSS: true }` and `{ importBootstrapTheme: true }` are ignored when depending on `ember-cli-sass`~~ (#1998) (not critical, not easy to achieve, moving out of scope)
- [x] Remove deprecated `buttonType` argument from `<BsButton>`(#1913)
- [x] Drop support for node 16 (#1961)
- [x] Drop support for Ember < 4.8 (#1996)

**Comment by jelhan** [comment]
I just released [`v6.0.0-0`](https://github.com/ember-bootstrap/ember-bootstrap/releases/tag/v6.0.0-0).

**Comment by vst** [comment]
> I just released [`v6.0.0-0`](https://github.com/ember-bootstrap/ember-bootstrap/releases/tag/v6.0.0-0).

It is not on NPM, right?

**Comment by jelhan** [comment]
> > I just released [`v6.0.0-0`](https://github.com/ember-bootstrap/ember-bootstrap/releases/tag/v6.0.0-0).
> 
> It is not on NPM, right?

It is: https://www.npmjs.com/package/ember-bootstrap/v/6.0.0-0

It's a prerelease. You won't get it until explicit requesting it. E.g. `yarn add --dev ember-bootstrap@^6.0.0-0`.

**Comment by jelhan** [comment]
> check our use of dependencies, especially with regard to peerDependencies. Some things we have as a dependency should probably be a peerDependency (e.g. @glimmer/component), which could be seen as a breaking change.
> 
> I enjoy the privilege of having the SME (subject matter expert) on pnpm and peerDependencies as a collegue (@NullVoxPopuli), so he might be able to advise?

@simonihmig Did you had a chance to discuss with @NullVoxPopuli? I moved `@glimmer/component` and `@glimmer/tracking` to peer dependencies in #1870. We already had `ember-source` as a peer dependency. Not sure about the many other dependencies. None of them is in default blueprint. Not sure if that should be the criteria though.

**Comment by jelhan** [comment]
Just released [`v6.0.0-3`](https://github.com/ember-bootstrap/ember-bootstrap/releases/tag/v6.0.0-3). I plan doing another release candidate soonish including the remaining breaking changes. But wanted to publish the extended ranges for dependencies as soon as possible to stop forcing people using overwrites or ignoring peer dependency issues with ember-source >= 5.0.

**Comment by jelhan** [comment]
I published [`v6.0.0`](https://github.com/ember-bootstrap/ember-bootstrap/releases/tag/v6.0.0).
