### ISSUE TITLE
Support Ember Modifier v4

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#1842]
This issues provides an overview of needed changes to support `ember-modifier@^4` in Ember Bootstrap.

- [x] Support `ember-style-modifier@^2` (#1826)
- [x] Support `ember-ref-bucket@^5` (#1841)
- [x] Support `ember-popper-modifier@^3` (#1852)
- [x] Remove `ember-modifier@3.2.7` resolution (#1853)

Support for Ember Modifier v4 requires some breaking changes. Therefore it is expected to land as `6.0.0` or in a later minor version.

You can force `ember-modifier@^4` using [Yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) as an interim solution.

**Comment by jelhan** [comment]
It seems that tests are failing with `ember-modifier@^4`. Needed to pin it to v3 in #1826. See https://github.com/ember-bootstrap/ember-bootstrap/pull/1826/files#r1071373604. Bugs were also reported on Discord. But missing reproduction so far.

**Comment by jelhan** [comment]
[`v6.0.0-0`](https://github.com/ember-bootstrap/ember-bootstrap/releases/tag/v6.0.0-0) supports `ember-modifier@^4`. Will track all issues, which might be discovered during beta phase as regular bugs.
